### ISSUE TITLE
Improve Contributor documentation

### ISSUE THREAD

**Issue by tabowling** [linux-system-roles/linux-system-roles.github.io#12]
A could reference example might be https://cockpit-project.org/external/wiki/Contributing.html

**Comment by Klaas-** [comment]
Is there a recommendation on ansible versions that need to be supported by the playbooks within the linux-system-roles namespace? Is that project specific?

**Comment by pcahyna** [comment]
@Klaas- all currently supported versions of Ansible : https://access.redhat.com/support/policy/updates/ansible-engine

**Comment by richm** [comment]
done - https://linux-system-roles.github.io/contribute.html
