### ISSUE TITLE
sshd system role configuration fails on FIPS enabled RHEL7 systems

### ISSUE THREAD

**Issue by btsimon97** [linux-system-roles/linux-system-roles.github.io#66]
We are attempting to use the SSH system role on RHEL7 systems which are in FIPS mode due to a security policy requirement. When trying to run this role through Ansible the playbook fails at SSH key generation task with error message "ED25519 keys are not allowed in FIPS mode". This is because the ed225519 key type is not available, as noted here: https://access.redhat.com/solutions/3643252.

Playbook likely needs to either detect if FIPS mode is enabled by getting the value of crypto.fips.enabled from sysctl, provide user method to specify which key algorithms to generate, or provide a FIPS variable that user can set to indicate if system is in FIPS mode.

**Comment by richm** [comment]
Which version of the sshd role are you using?

**Comment by btsimon97** [comment]
Version 1.0.1 from Red Hat's Ansible Automation hub (https://cloud.redhat.com/ansible/automation-hub/repo/published/redhat/rhel_system_roles), not sure what upstream version it corresponds with.

**Comment by richm** [comment]
ok - in the meantime, as a workaround, you could manually set `sshd_HostKey` or `sshd.HostKey` to the list of hostkey files omitting the ed25519 key https://github.com/willshersystems/ansible-sshd/blob/master/vars/RedHat_7.yml#L7 
e.g. in your inventory
```
sshd_HostKey:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_ecdsa_key
```

**Comment by btsimon97** [comment]
Have tested the described workaround and it works properly, allowing the playbook to run properly on FIPS enabled systems. Thank you!
